apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: app
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
