apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: app
data:
  nginx.conf: |
    events {
        worker_connections 1024;  # Set the max number of simultaneous connections
    }

    http {
        # Load balancer configuration
        server {
            listen 80;
            server_name _;

            # Redirect HTTP to HTTPS
            return 301 https://$host$request_uri;
        }

        server {
            listen 443 ssl;
            server_name _;

            # SSL configuration
            ssl_certificate /etc/nginx/certs/fullchain.pem;
            ssl_certificate_key /etc/nginx/certs/privkey.pem;
            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_prefer_server_ciphers on;

            # Proxy settings
            location / {
                proxy_pass http://flask-app-service:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            # Basic auth for /admin
            location /admin {
                auth_basic "Restricted Access";
                auth_basic_user_file /etc/nginx/.htpasswd;
                proxy_pass http://flask-app-service:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            # Block /prepare-for-deploy and /ready-for-deploy
            location /prepare-for-deploy {
                deny all;
                return 403;
            }

            location /ready-for-deploy {
                deny all;
                return 403;
            }
        }
    }

