apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: app
type: Opaque
data:
  mariadb-root-password: aGVzbG8K 
  mariadb-app-password: aGVzbG8K
  mariadb-developer-password: aGVzbG8K
