apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: app
type: Opaque
data:
  mariadb-root-password: cGFzcw==
  mariadb-app-password: cGFzcw==
  mariadb-developer-password: cGFzcw==
