apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-script
  namespace: app
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS db;
    CREATE USER IF NOT EXISTS 'app_user'@'%' IDENTIFIED BY '${MARIADB_APP_PASSWORD}';
    CREATE USER IF NOT EXISTS 'developer'@'%' IDENTIFIED BY '${MARIADB_DEVELOPER_PASSWORD}';
    GRANT ALL PRIVILEGES ON db.* TO 'app_user'@'%';
    GRANT SELECT ON db.* TO 'developer'@'%';
    FLUSH PRIVILEGES;
