apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: app
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-root-password
            - name: MARIADB_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-app-password
            - name: MARIADB_DEVELOPER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-developer-password
          command:
            - sh
            - -c
            - |
              chmod +x /scripts/generate-init-sql.sh
              /scripts/generate-init-sql.sh
              exec docker-entrypoint.sh mysqld
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
            - name: mariadb-init
              mountPath: /docker-entrypoint-initdb.d
            - name: script-volume
              mountPath: /scripts
      volumes:
        - name: mariadb-init
          configMap:
            name: mariadb-init-script
        - name: script-volume
          configMap:
            name: mariadb-init-script
  volumeClaimTemplates:
    - metadata:
        name: mariadb-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
