
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: nevimkamouz/flask-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
            - name: APP_HOST
              value: "0.0.0.0"
            - name: APP_PORT
              value: "5000"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: DB_NAME
              value: db
            - name: DB_HOST
              value: mariadb-0.mariadb.app.svc.cluster.local
            - name: DB_USER
              value: "app_user"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-app-password
          readinessProbe:
            httpGet:
              path: /status
              port: 5000
            initialDelaySeconds: 20   
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /status
              port: 5000
            initialDelaySeconds: 30  
            periodSeconds: 10
            failureThreshold: 3
